version: "3.8"
services:
  app:
    build:
      context: .
    container_name: filter_on_tags
    env_file: .env
    restart: always
    volumes:
      - ./src:/app
    command: python main.py
    ports:
      - "5000:5000"
